### ISSUE TITLE
Migrate vault challenge to Cairo v2

### ISSUE THREAD

**Issue by devnet0x** [devnet0x/Starknet-Security-Challenges-Factory#18]
Migrate Challenge 12 (Vault) to Cairo v2 (in src/assets directory).

**Comment by Mohiiit** [comment]
I would like to work on it!

**Comment by Mohiiit** [comment]
Hey, I have developed the code but I am not sure how can I test it out. What I have tried so far is: get the transaction hash and try making the password on my side but I hit the wall there.

**Comment by devnet0x** [comment]
Password is self created on constructor. Once deployed you should read password memory address where this variable is stored in the contract. Here you will find a javascript with solution: https://github.com/starknet-edu/starknetbook/blob/f0c330ca6e4d4365751957ca42dc155ef4c3d174/src/ch02-13-04-security-considerations.md#5-private-data-on-chain

**Comment by Mohiiit** [comment]
thanks for your help, I was able to test it out. here is the pull request: https://github.com/devnet0x/Starknet-Security-Challenges-Factory/pull/19
