### ISSUE TITLE
Migrate challenge 14 from  Cairo 1 to Cairo 2

### ISSUE THREAD

**Issue by devnet0x** [devnet0x/Starknet-Security-Challenges-Factory#21]
Migrate 3 contracts of challenge 13 from  Cairo 1 to Cairo 2

**Comment by TAdev0** [comment]
@devnet0x  same here, i have migrated these contracts with last 2.4 syntax. Can make a PR if you want :)

**Comment by devnet0x** [comment]
Thanks, please send your PR.
