### ISSUE TITLE
Migrate challenge 8 "Insecure DEX" to Cairo 2

### ISSUE THREAD

**Issue by devnet0x** [devnet0x/Starknet-Security-Challenges-Factory#23]
Migrate challenge 8 "Insecure DEX" to Cairo 2

**Comment by ArturVargas** [comment]
Hi @devnet0x this issue is related with all Cairo contracts that is named as challenge8?

**Comment by devnet0x** [comment]
yes, all 4 contracts: challenge8_main, challenge8_dex, challenge8_erc20, challenge8_erc223;

**Comment by ArturVargas** [comment]
Great Can I take this @devnet0x ?

**Comment by devnet0x** [comment]
Assigned @ArturVargas

**Comment by TAdev0** [comment]
@ArturVargas  are you working on this issue?

**Comment by ArturVargas** [comment]
> @ArturVargas are you working on this issue?

Hi @TAdev0 I was working on that, but currently I don't have enough time to finish this issue here is my progress https://github.com/ArturVargas/Starknet-Security-Challenges-Factory/tree/fix/updateCairoInsecureDex

**Comment by TAdev0** [comment]
great!

**Comment by TAdev0** [comment]
@ArturVargas if you don't have time i can work on it :)

**Comment by devnet0x** [comment]
Closed with PR#48
