### ISSUE TITLE
Hardcoded SN_GOERLI Class Hashes - Challenges 7, 14 cannot be deployed on SN_SEPOLIA

### ISSUE THREAD

**Issue by zmalatrax** [devnet0x/Starknet-Security-Challenges-Factory#42]
The challenges 7 and 14 cannot be deployed on Sepolia as the class hashes of the sub-contracts are hardcoded and not to be found on Sepolia (remainder from Goerli).

Challenge 7 - VTOKEN - ERC20: [L46-L48](https://github.com/devnet0x/Starknet-Security-Challenges-Factory/blob/c1f9d6db576aacf28c403a2b1b44f349e4eaf70c/src/assets/challenge7.cairo#L46-L48)

Challenge 14 - GOOD SAMARITAN: Wallet [L41-L43](https://github.com/devnet0x/Starknet-Security-Challenges-Factory/blob/c1f9d6db576aacf28c403a2b1b44f349e4eaf70c/src/assets/challenge14.cairo#L41-L43) & Coin [L50-L52](https://github.com/devnet0x/Starknet-Security-Challenges-Factory/blob/c1f9d6db576aacf28c403a2b1b44f349e4eaf70c/src/assets/challenge14.cairo#L50-L52)

A quick fix would be declaring contracts on Sepolia, changing hardcoded class hashes and redeploying the challenges.

A more sustainable fix would also implements getter/setter for contract's class hashes that need to be deployed in a challenge, with proper access-control.

**Comment by devnet0x** [comment]
Thanks @zmalatrax , issue fixed.
