### ISSUE TITLE
Challenge 5 - Improper class hash challenge

### ISSUE THREAD

**Issue by zmalatrax** [devnet0x/Starknet-Security-Challenges-Factory#43]
The challenge_class_hash set for Challenge 5 - SECRET is `0x05141d769ce5dffd00a2cbd210c41a443360d68fd19a050c8cba22224d786918`, i.e.the [Challenge Factory - main contract](https://sepolia.starkscan.co/contract/0x05141d769ce5dffd00a2cbd210c41a443360d68fd19a050c8cba22224d786918#overview)

Thus, the challenge cannot be deployed on Sepolia.

Please update the challenge_class_hash 🙏 

![challenge_5_classh_hash](https://github.com/devnet0x/Starknet-Security-Challenges-Factory/assets/71888134/6926dfd7-6f26-44cd-8fd4-88cff154c48c)

**Comment by devnet0x** [comment]
Thanks @zmalatrax  fixed with the correct class_hash 0x06d0df876ccc14e88e4cbcaf01c327b3a98f432fc42819df223cb89f740e8ee3
