### ISSUE TITLE
Migrate challenges Guess, Secret and Random from Cairo 0 to Cairo 2

### ISSUE THREAD

**Issue by devnet0x** [devnet0x/Starknet-Security-Challenges-Factory#6]
Migrate this 3 challenges from Cairo 0 to Cairo 1. Then PR updated challenge source code in src/assets directory.

**Comment by tonyprometeo** [comment]
hi devnet0x, can i be assigned on this issue ? i can start now.

**Comment by devnet0x** [comment]
Thanks @tonyprometeo , issue closed with PR #40
