### ISSUE TITLE
Migrate challenge Fallout to Cairo 2

### ISSUE THREAD

**Issue by devnet0x** [devnet0x/Starknet-Security-Challenges-Factory#8]
Migrate challenge Fallout to Cairo 1. (In src/assets directory)

**Comment by ArturVargas** [comment]
Hi @devnet0x I can't find this file

**Comment by TAdev0** [comment]
@devnet0x  i just did the migration to cairo 2 for this challenge :)

**Comment by devnet0x** [comment]
Thanks @TAdev0 i'm going to test it.
